//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatCho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatCho()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int MaDatCho { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaTour { get; set; }
        public int SoLuongNguoi { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TourDuLich TourDuLich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
