//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiemDen()
        {
            this.TourDuLiches = new HashSet<TourDuLich>();
        }
    
        public int MaDiemDen { get; set; }
        public string TenDiemDen { get; set; }
        public string MoTa { get; set; }
        public string ViTri { get; set; }
        public string LinkAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourDuLich> TourDuLiches { get; set; }
    }
}
